---
# file: tasks/sw_ansible-push.yml

- name: Add PPA repository for ansible
  apt_repository: repo="ppa:rquillo/ansible"
                  state=present
  tags:
    - repository

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - repository

- name: Install packages for ansible
  apt: pkg={{ item }} 
       state=present
  with_items:
    - ansible
  tags:
    - packages
