---
# file: tasks/sw_ntp-client.yml

- name: Install ntp packages
  apt: pkg={{ item }} state=present
  with_items: 
    - ntp
    - ntpdate
  tags: 
    - packages

- name: Configure ntpd
  template: src=etc/ntp.conf.j2 
            dest=/etc/ntp.conf
  notify: 
    - Restart ntpd
  tags: 
    - configuration

- name: Ensure ntpd is running
  service: name=ntp state=running enabled=yes
  tags: 
    - check
