---
# file: tasks/sw_squid.yml

- name: Install squid packages
  apt: pkg={{ item }} 
       state=present
  with_items: 
    - squid
  tags: 
    - packages

- name: Configure squid
  template: src={{ item }}.j2
            dest=/{{ item }}
            owner=root
            group=root
            mode=00644
  with_items:
    - etc/squid3/squid.conf
    - etc/squid3/msntauth.conf
  notify: 
    - Restart squid
  tags:
    - configuration

- name: Ensure squid is running
  service: name=squid3
           state=running
           enabled=yes
  tags: 
    - check
