---
# file: tasks/sw_ufw.yml

- name: Install package(s) for ufw
  apt: pkg={{ item }} 
       state=present
  with_items: 
    - ufw
  tags: 
    - install

- name: Ensure ntpd is running
  service: name=ntp state=running enabled=yes
  tags: 
    - check
