---
# file: tasks/sw_zookeeper-server.yml

- name: Obtain Cloudera CDH4 repository key
  apt_key: url=http://archive.cloudera.com/cdh4/ubuntu/precise/amd64/cdh/archive.key
           state=present
  tags:
    - repository

- name: Add Cloudera CDH4 repository
  apt_repository: repo='deb [arch=amd64] http://archive.cloudera.com/cdh4/ubuntu/precise/amd64/cdh precise-cdh4 contrib' 
                  state=present
  tags:
    - repository

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - repository

- name: Install packages for zookeeper-server
  apt: pkg={{ item }} 
       state=present
  with_items:
    - zookeeper
    - zookeeper-server
  tags:
    - packages

- name: Configure packages for zookeeper-server
  template: src=zoo.cfg.j2 
            dest=/etc/zookeeper/conf/zoo.cfg
  tags:
    - configuration
